version = 1
SPDX-PackageName = "capire-samples-java"
SPDX-PackageSupplier = "The cap team <cap@sap.com>"
SPDX-PackageDownloadLocation = "https://github.com/capire/samples-java"
SPDX-PackageComment = "This project demonstrates how to set up a monorepo with multiple SAP CAP microservices and deploy them to SAP BTP using a single shared database instance."

[[annotations]]
path = "**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 SAP SE or an SAP affiliate company and cds-dbs contributors"
SPDX-License-Identifier = "Apache-2.0"
